### ISSUE TITLE
Application freezes before conversion is complete

### ISSUE THREAD

**Issue by renaldofreire** [flathub/io.github.ciromattia.kcc#2]
Hi, thanks for making the application available on flathub. I am having problems with conversion.

At a certain point (as shown below) the program freezes and does not finish the conversion.

I am using arch linux with DE Gnome 41.3.

<a href="https://ibb.co/k06wbmj"><img src="https://i.ibb.co/K7zf4Kd/2022-01-27-05-11.png" alt="2022-01-27-05-11" border="0"></a>

### Error Log
```
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
Gtk-Message: 05:20:59.194: Failed to load module "canberra-gtk-module"
Gtk-Message: 05:20:59.194: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
libpng warning: iCCP: known incorrect sRGB profile
libGL error: MESA-LOADER: failed to retrieve device information
Preparing source images...
Checking images...
Processing images...
Creating EPUB file...
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/KindleComicConverter-5.5.2-py3.9.egg/kindlecomicconverter/KCC_gui.py", line 417, in run
    epubSize = (os.path.getsize(self.kindlegenErrorCode[2])) // 1024 // 1024
  File "/usr/lib/python3.9/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
OSError: [Errno 107] Transport endpoint is not connected: '/run/user/1000/doc/95d2fce8/Battle Royale, v01 (2000) [TokyoPop] [Manga-Sketchbook].epub'

```

**Comment by catsout** [comment]
Try to add `host` filesystem permission through `flatseal`.  
Need to make sure the file path is not like `/run/user/....`.

**Comment by renaldofreire** [comment]
@catsout Thank you! That solved the problem.
